# -*- coding: utf-8 -*-
"""Maximizar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DgLLIwnZJb9yL5ELctYeP_I0hXLDUaCy
"""

!pip install pulp

import pandas as pd
from pulp import LpProblem, LpVariable, LpMaximize, lpSum, LpBinary, LpStatus, value

# === 1. Cargar la base de datos ===
df = pd.read_csv('database.csv')

df.columns

# === 2. Limpiar y preparar ===

# Asegurar tipo numérico para montocobrado
df['montocobrado'] = pd.to_numeric(df['montocobrado'], errors='coerce')

# Quitar intentos con monto no cobrado
df = df[df['montocobrado'].notna()].copy()

# Crear índice único por intento
df = df.reset_index(drop=True)
df['var_id'] = df.index

# === 3. Crear el modelo ===
modelo = LpProblem("Maximizacion_Cobranza", LpMaximize)

# Variables binarias por intento
x = LpVariable.dicts("x", df['var_id'], cat=LpBinary)

# Función objetivo: Maximizamos la suma de lo cobrado
modelo += lpSum(x[i] * df.loc[i, 'montocobrado'] for i in df['var_id']), "TotalCobrado"

# Restricción: una sola selección por idcredito
for credito in df['idcredito'].unique():
    indices = df[df['idcredito'] == credito]['var_id']
    modelo += lpSum(x[i] for i in indices) <= 1, f"UnIntento_{credito}"

# === 4. Resolver ===
modelo.solve()

# === 5. Resultados ===
print(f"Estado del modelo: {LpStatus[modelo.status]}")
print(f"Total máximo cobrado: ${value(modelo.objective):,.2f}")

# Guardar solución
df['seleccionado'] = df['var_id'].apply(lambda i: x[i].varValue)
seleccion_optima = df[df['seleccionado'] == 1].copy()

# Opcional: exportar resultado
seleccion_optima.to_csv('solucion_maximizacion_cobranza.csv', index=False)
print("✅ Resultado exportado como 'solucion_maximizacion_cobranza.csv'")

# Agrupar la solución por emisora, banco y tipo de envío
estrategia = seleccion_optima.groupby(['emisora', 'banco', 'tipoenvio']).agg(
    num_creditos=('idcredito', 'count'),
    total_cobrado=('montocobrado', 'sum'),
    monto_promedio=('montocobrado', 'mean')
).reset_index()

# Ordenar por total cobrado
estrategia = estrategia.sort_values(by='total_cobrado', ascending=False)

# Mostrar el top 5 de combinaciones más efectivas
print("🎯 Estrategias ganadoras:")
print(estrategia.head(5))